version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
    links:
      - gitlab:gitlab

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    expose:
      - "80"
    ports:
      - "2224:22"
    volumes:
      - /etc/gitlab/config:/etc/gitlab
      - /var/log/gitlab:/var/log/gitlab
      - /etc/gitlab/data:/var/opt/gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

## config for nginx
server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://gitlab;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
